### PR TITLE
Add Kenny

### PR DESCRIPTION
**Pull request by kennyrowe**
Adding kenny to team page

### CODE REVIEW

**Comment by matildepark** [comment]
Heh, did you run the picture by @galenwp? It's close, but not exact, with the other pics, and idk how much he cares.

**Comment by matildepark** [comment]
The image itself should just also be hosted on media.urbit.org. I can do that if you want.

**Comment by kennyrowe** [comment]
No I did not run by Galen so if he disapproves I will just got with my
sigil. If he’s ok with it sure pleas upload to Tlon media server.

Kenny

**Comment by galenwp** [comment]
Hm!

Yeah, I think it'd be weird to have one image that's inconsistent. Although in a COVID world I have no idea how we're going to get photos of people — obviously we're going to need a different solution here eventually.

Let's just go with your sigil for now.

**Review by urcades — APPROVED** [review]

**Pull request merged**
