### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by crrncllns**
Remove invitation to apply

### CODE REVIEW

**Review by g-a-v-i-n — APPROVED** [review]
LGTM

**Comment by Fang-** [comment]
Heads up that we also have [this big ol' thing](https://github.com/urbit/bridge/blob/f08b3ccc73726ceccc2bea34a45fc7d31dfd1488/src/index.js#L11) in Bridge, printed to the web console. Should we get that out of there?

**Comment by crrncllns** [comment]
Yes, good call.

**Comment by crrncllns** [comment]
@g-a-v-i-n I don't have write access so I can't merge

**Pull request closed without merging**
