### PR TITLE
add christian

### PR DESCRIPTION
**Pull request by matildepark**
Adds Christian to directory. Unsure what dept we put him under — just went with "Operations", but welcoming suggestion.

### CODE REVIEW

**Comment by galenwp** [comment]
Seems fine to me

**Review by galenwp — APPROVED** [review]

**Comment by vvisigoth** [comment]
SFTM
—
~poldec-tonteg
http://urbit.org

**Comment by bioy-casares** [comment]
Vainglory!  I would propose Interface as my category, as that's what my contract lists. 

Thanks Matilde.

**Comment by matildepark** [comment]
Aight.

**Pull request merged**
